# Generated by Django 3.0.7 on 2020-06-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('headtitle', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('para1', models.TextField()),
                ('para2', models.TextField()),
                ('heading2', models.CharField(max_length=50)),
                ('para3', models.TextField()),
                ('featureimage', models.ImageField(default='', upload_to='blog/featureimages')),
                ('imagep1', models.ImageField(blank=True, default='', upload_to='blog/projectimages')),
                ('imagep2', models.ImageField(default='', upload_to='blog/projectimages')),
                ('imagep3', models.ImageField(default='', upload_to='blog/projectimages')),
                ('imagep4', models.ImageField(default='', upload_to='blog/projectimages')),
                ('imagep5', models.ImageField(default='', upload_to='blog/projectimages')),
                ('imagep6', models.ImageField(default='', upload_to='blog/projectimages')),
            ],
        ),
    ]
