# Generated by Django 3.0.7 on 2020-06-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imagep1',
            field=models.ImageField(default='', upload_to='blog/projectimages'),
        ),
        migrations.AlterField(
            model_name='article',
            name='imagep4',
            field=models.ImageField(blank=True, default='', upload_to='blog/projectimages'),
        ),
        migrations.AlterField(
            model_name='article',
            name='imagep5',
            field=models.ImageField(blank=True, default='', upload_to='blog/projectimages'),
        ),
        migrations.AlterField(
            model_name='article',
            name='imagep6',
            field=models.ImageField(blank=True, default='', upload_to='blog/projectimages'),
        ),
    ]
